# Generated by Django 4.1.2 on 2022-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='register_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
