# Generated by Django 4.1.3 on 2022-11-11 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('company', 'company'), ('consultant', 'consultant')], default='company', max_length=25)),
                ('gst_in', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=75)),
                ('state', models.CharField(blank=True, max_length=75)),
                ('country', models.CharField(blank=True, max_length=75)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employerModel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=75, null=True)),
                ('last_name', models.CharField(blank=True, max_length=75, null=True)),
                ('date_of_birth', models.DateField(blank=True, default='2001/01/01')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('city', models.CharField(blank=True, max_length=75)),
                ('state', models.CharField(blank=True, max_length=75)),
                ('country', models.CharField(blank=True, max_length=75)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidateModel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
