# Generated by Django 4.1.3 on 2022-11-11 07:55

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_user_is_candidate_user_is_employer_employermodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update_At',
            new_name='update_at',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True, verbose_name='mobile number'),
        ),
    ]
