# Generated by Django 4.1.3 on 2022-11-11 09:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_rename_update_at_user_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91818053481', max_length=128, region=None, verbose_name='mobile number'),
        ),
    ]
